import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import clsx from "clsx";
import { poppins } from "./fonts";
import { logoFont } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container mx-auto py-8 px-8 sm:px-auto">
        <nav
          className={clsx(
            logoFont.className,
            "text-2xl flex items-start gap-12"
          )}
        >
          <Link href="/">Home</Link>
          <Link href="/blog">Blog</Link>
          <Link href="/about">About</Link>
        </nav>
        <main className={clsx(poppins.className, "mt-12")}>{children}</main>
      </body>
    </html>
  );
}
